### ISSUE TITLE
Fancy discord not displaying in swing

### ISSUE THREAD

**Issue by Ferrariic** [NeverScapeAlone/never-scape-alone#139]
𝓦𝓸𝓸๔𝓼𝓴𝓲#4727 -> ???????#4727

Previously a fatal bug now downgraded to a bug. 

Fatal bug ref: #135 

![image](https://user-images.githubusercontent.com/5789682/184759195-e6f69ae9-be99-426c-9dcd-8e7072accb70.png)

```
java.lang.IllegalArgumentException: Illegal base64 character 23
    at java.base/java.util.Base64$Decoder.decode0(Unknown Source)
    at java.base/java.util.Base64$Decoder.decode(Unknown Source)
    at java.base/java.util.Base64$Decoder.decode(Unknown Source)
    at com.neverscapealone.ui.PlayerPanelClass.createPlayerPanel(PlayerPanelClass.java:129)
    at com.neverscapealone.ui.NeverScapeAlonePanel.setMatchPanel(NeverScapeAlonePanel.java:396)
    at com.neverscapealone.ui.NeverScapeAlonePanel.lambda$onMatchData$1(NeverScapeAlonePanel.java:259)
    at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
    at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
    ```

**Comment by Ferrariic** [comment]
This is likely impossible to fix to be honest, just due to how the formatting and encoding works
