### ISSUE TITLE
Lobby Closure

### ISSUE THREAD

**Issue by Ferrariic** [NeverScapeAlone/never-scape-alone#216]
```
{"ts": "2022-09-14 02:02:32,027", "name": "api.routers.lobby", "function": "websocket_endpoint", "level": "DEBUG", "msg": "\"Carboxyde => 1000 | did-tofu-burgh\""}
{"ts": "2022-09-14 02:02:32,027", "name": "api.routers.lobby", "function": "websocket_endpoint", "level": "DEBUG", "msg": "\"xx => Normal Socket Closure\""}
{"ts": "2022-09-14 02:02:32,073", "name": "api.routers.lobby", "function": "websocket_endpoint", "level": "DEBUG", "msg": "\"xx => Cannot call "send" once a close message has been sent.\""}
Traceback (most recent call last):
  File "/code/./api/routers/lobby.py", line 127, in websocket_endpoint
    await handle_request(
  File "/code/./api/routers/interactions/handler.py", line 147, in handle_request
    await update_status(
  File "/code/./api/routers/interactions/functions.py", line 482, in update_status
    await manager.broadcast(group_identifier=group_identifier, payload=payload)
  File "/code/./api/utilities/manager.py", line 255, in broadcast
    await connection.send_json(payload)
  File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 137, in send_json
    await self.send({"type": "websocket.send", "text": text})
  File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 70, in send
    raise RuntimeError('Cannot call "send" once a close message has been sent.')
RuntimeError: Cannot call "send" once a close message has been sent.

{"ts": "2022-09-14 02:02:32,084", "name": "api.routers.lobby", "function": "websocket_endpoint", "level": "DEBUG", "msg": "\" xx=> Cannot call "send" once a close message has been sent.\""}
Traceback (most recent call last):
  File "/code/./api/routers/lobby.py", line 127, in websocket_endpoint
    await handle_request(
  File "/code/./api/routers/interactions/handler.py", line 147, in handle_request
    await update_status(
  File "/code/./api/routers/interactions/functions.py", line 482, in update_status
    await manager.broadcast(group_identifier=group_identifier, payload=payload)
  File "/code/./api/utilities/manager.py", line 255, in broadcast
    await connection.send_json(payload)
  File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 137, in send_json
    await self.send({"type": "websocket.send", "text": text})
  File "/usr/local/lib/python3.10/site-packages/starlette/websockets.py", line 70, in send
    raise RuntimeError('Cannot call "send" once a close message has been sent.')
RuntimeError: Cannot call "send" once a close message has been sent.
```

**Comment by Ferrariic** [comment]
Should be resolved now, in theory
